### ISSUE TITLE
Setup notes: MetalLB

### ISSUE THREAD

**Issue by magsol** [bplein/post-talos-setup#1]
It looks like our configurations are just about identical, with a couple small exceptions:

 - I combined the L2Advertisement and IPAddressPool directives into a single yaml.
 - My L2Advertisement has a `spec:` field containing `ipAddressPools: my-pool`.
 - My IPAddressPool has an `autoAssign: true`.

Pretty sure these changes don't make any substantive difference but wanted to record them anyway.

**Comment by bplein** [comment]
If you include an anonymized version here, I can see if it makes sense to change it to your version. Thanks!

**Comment by magsol** [comment]
First I installed metallb via helm:

```bash
helm install metallb metallb/metallb \
    --create-namespace \
    --namespace metallb
```

Then I applied the custom config, reproduced below:

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.1.100-192.168.1.150
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: base-l2-advertise
  namespace: metallb
spec:
  ipAddressPools:
  - my-pool
```

This is pretty much it, verbatim.
